### ISSUE TITLE
Make language setting stable

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-js#2262]
Tolgee stores language option in localStorage and doesn't keep a copy of it locally. If you switch language in different tab it can lead to half page in original language and half in new language.

**Comment by stepan662** [comment]
![Snímek obrazovky 2022-03-11 v 9 07 49](https://user-images.githubusercontent.com/8831144/157828094-19561ab2-428f-40b3-bbc7-55c0335bcb17.png)

**Comment by JanCizmar** [comment]
Haha! 🔥
