### ISSUE TITLE
Create Tolgee CLI

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-js#2419]
Create CLI which should:
- [ ] Export data from Tolgee to specific dir
- [ ] Import data to Tolgee using Import endpoints
- [ ] Analyse code for unused keys / keys missing in Tolgee

**Comment by stophecom** [comment]
I guess this one can be closed now https://github.com/tolgee/tolgee-cli exists :)

**Comment by JanCizmar** [comment]
It still doesn't export the data and it's not published in npm, so I wouldn't close it yet. :)

**Comment by Raaghav4243** [comment]
Hey I would like to work on this feature.
Reference : Aviyel
Could you please assign it to me
Thanx

**Comment by JanCizmar** [comment]
Hi there! Actually, there is a Repo for that, which is already prepared for further work! If you would like to dig in, I can create some issues there. 
https://github.com/tolgee/tolgee-cli

**Comment by JanCizmar** [comment]
Comment there, and I can assign some to you.
https://github.com/tolgee/tolgee-cli/issues

**Comment by JanCizmar** [comment]
It's done in separate repo.
