### ISSUE TITLE
[Feature request] Automated screenshot without browser extension

### ISSUE THREAD

**Issue by KaKi87** [tolgee/tolgee-js#2428]
For compatibility with [Tauri](https://tauri.studio/) & [Electron](https://www.electronjs.org/) apps.

Thanks

**Comment by JanCizmar** [comment]
Interesting Idea! Will look to implementation option of such feature. But it would probably be doable!

**Comment by stepan662** [comment]
We might use https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia?ref=hackernoon.com instead. But I'm not sure how it works in Tauri and Electron ...

**Comment by KaKi87** [comment]
It should work fine.

**Comment by KaKi87** [comment]
Hello,
Was this implemented ?
Thanks

**Comment by stepan662** [comment]
Hey, no, I didn't find the solution very pratical, so I've decided to skip this.
