### ISSUE TITLE
Add namespace support

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-js#2733]

**Comment by Marr11317** [comment]
What exactly do you call namespaces?

**Comment by JanCizmar** [comment]
Sometimes you want to split translations in separate files for some part of the app. Especially when you build large system, localization data can get larger and you would need to split it somehow.

However @stepan662 is working on new core implementation, so it will be covered by it. https://github.com/tolgee/tolgee-js/issues/3077
