### ISSUE TITLE
Libraries have a massive footprint

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-js#2967]
I was looking at the footprint of the JS libraries, and was quite disappointed to see that the `@tolgee/react` package was almost 100KB (~27KB gzipped), which felt quite heavy considering the Preact library (which is a drop-in replacement for React) is ~21KB (9KB gzipped) even with all the extra compatibility tools for React compatibility (`preact/compat`). Here's the [bundlejs.com link](https://bundlejs.com/?q=@tolgee/react&treeshake=[{+TolgeeProvider,T+}]&config={%22analysis%22:true,%22alias%22:{%22react%22:%22preact/compat%22,%22react-dom%22:%22preact/compat%22}}) for more details.

This is actually problematic as on the web bundle size matters a lot, and in my case importing Tolgee's React library would triple the size of my web application's JS bundle. And, seeing that most of the weight of the bundle is located in `@tolgee/core`, this has a cascading effect on all integrations.

It appears that features useful for development environments only (e.g. screenshots) gets bundled along with the core package, and because it doesn't have to be imported separately, tree-shaking doesn't eliminate this code and it gets bundled in the final application, which is terrible for the final bundle.

I know making the lib as lightweight as possible is difficult and may be out of scope, but there seem to be a lot of low-hanging fruits that would help greatly enhancing the library on this aspect, and make people like me who take bundle size very seriously happy 😺

**Comment by JanCizmar** [comment]
Hi @cyyynthia! Again, you're right. The largest part of the @tolgee/core is the ICU formatter. Stepan already started working on refactored / smaller, @tolgee/core.

**Comment by stepan662** [comment]
It's not really low hanging fruit, but I definitely want to make it smaller. Thanks for your input 🙂

**Comment by cyyynthia** [comment]
> It's not really low hanging fruit

Well, eliminating dead code doesn't sound that hard to me; I haven't looked at the guts of the libraries but this alone would have a significant impact, by gating development-only parts behind `process.env.NODE_ENV`, so bundlers can wipe away this code. Unless things are tied together a bit too tightly for that, it shouldn't be too difficult to do. While exploring the bundle, there were some parts that felt unrelated to a production-env (e.g. screenshot related stuff).

Rewriting core parts to be as compact as possible sure isn't though! Good luck with that, and thanks for working on it 😄

**Comment by Marr11317** [comment]
I don't get it: Looking at the react bundlejs.com link, it sure is the ICU formatter that makes up for these Kilobytes, but doing the same with the svelte implementation yields a 1KB bundle.

```ts
export { TolgeeProvider, T } from "@tolgee/svelte"; // -> 1.26KB (gzip)
```

```ts
export { TolgeeProvider, T } from "@tolgee/react"; // -> 29.04KB (gzip)
```

**Comment by cyyynthia** [comment]
The Svelte output generated by bundlejs.com is incomplete and you can see in the output that there are many `import`s which haven't been processed, unlike for the React build which does not include any `import` reference

**Comment by Marr11317** [comment]
Got it.

Unfortunately, for ICU, I don't see what can be done apart from writing an ICU to js compiler, and then download js files instead of strings from tolgee.

So when the ICU string is 

```json
{
    "key": "Message with a {value}"
}
```

What would be downloaded would be:

```js
export default {
    "key":  (value) => "Message with a " + value;
}
```

That would completely remove the need for the ICUFormatter being shipped to the client.

**Comment by cyyynthia** [comment]
ICU pre-processing is something that has been thought about and is being explored through a [vite plugin](https://github.com/tolgee/vite-plugin-i18n-tolgee) :eyes:

There are still ways to make the lib lighter while keeping a "traditional" approach to ICU handling, but you're right regarding pre-processing rather than handling the raw json file. 👍🏻

**Comment by JanCizmar** [comment]
@stepan662 is working on new @tolgee/core implementation, where we will support natively only simple parameters like `Hello I am {param}`. ICU formatter would be added as separate module, so user's would be able to choose whether they want full ICU support for price of ~20kb gzipped or whether they want to use just this simple way.

**Comment by stepan662** [comment]
https://github.com/tolgee/tolgee-js/pull/3109
