### ISSUE TITLE
Allow loading of localization files with hash in filename 

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-js#298]
Localization files have to be loaded every time the page is loaded since there is no way to cache it by their filename.

Lets enable server to export localization .jsons with single definition .json file with this example content:

```
{
    "languages": {
        "en": {
            name: "English",
            file: "en.7e2c49a622975ebd9b7e.json"
        }
        de": {
            name: "Deutsch",
            file: "de.6e2449a682975ebd9b6d.json"
        }
    }
}
```

This could be also source for items in language select menu.

**Comment by thran** [comment]
Any progress with this?

**Comment by JanCizmar** [comment]
Yes! Now it's possible to provide exported data using dynamic import or as an object. It's described in this doc page:
https://tolgee.io/docs/web/using_with_angular/angular_preparing_for_production
