### ISSUE TITLE
Gatsbyjs: Tolgee context is null for useTranslate

### ISSUE THREAD

**Issue by kmalkenneth** [tolgee/tolgee-js#3014]
The problem is simple, useTranslate doesn't work.
First imported the dependencies to use
```js
import { T, useTranslate } from "@tolgee/react";
```
When using useTranslate() gatsby says "**Tolgee context is null. Is this code executed inside TolgeeProvider component?**"
```js
const t = useTranslate()
```
But with the component it works.
```js 
<T keyName="article_author_label" ></T>
```
It seems that it only affects templates.

**Comment by JanCizmar** [comment]
Can you please share some example, where I can reproduce this? It works in this [example repo](https://github.com/tolgee/gatsby-example).
