### ISSUE TITLE
[Question] Vue: How to get/set language outside of a component, e.g. from a vuex store action ?

### ISSUE THREAD

**Issue by KaKi87** [tolgee/tolgee-js#3037]
Thanks

**Comment by stepan662** [comment]
I'm afraid thats not really possible and not even intended. Depends how you work with the store, however either you can store the language in the store and force Tolgee to use the same one. Or leave the language up to Tolgee and work with it only outside the store as store actions should be pure. We generally don't want to expose Tolgee instance globally as that might be limiting for the future.
