### ISSUE TITLE
Rewrite @tolgee/core

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-js#3077]
- [x] Make it tiny
- [x] Make everything which is not essential as an external module
- [x] Create a simple message format which would only support parameters passed in curly brackets `{}` and which is compatible with ICU, so users, who will add ICU module in the future wouldn't need to rewrite their messages
- [x] Support for namespaces / splitting translations into separate files
- [ ] Markdown support (as external module)
- [ ] Support for basic HTML tags (as external module)

**Comment by stepan662** [comment]
Mostly solved in https://github.com/tolgee/tolgee-js/pull/3109
