### ISSUE TITLE
Provide a "reviewed" checkbox in the in-context editor plugin

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-js#3079]
For my use case, marking a translation as reviewed "releases" the translation for the next step (until then, it will be modified by the API since it's the combination of two other independent translations and the user reviews it and makes final edits). It would be great if there was an option to mark the translation as reviewed when editing in-context so that the user doesn't have to go to the system, find the key, mark reviewed manually (or be confused as to why the API keeps changing their translation since it wasn't "locked" in our use case)
![image](https://user-images.githubusercontent.com/1071438/185034744-9b3b7fa1-b653-4937-8fce-1d3e9eb89a66.png)

**Comment by wfjsw** [comment]
It's also useful to somehow mark all translated string that are not yet reviewed on the page, or allow switching between showing reviewed only and all translated strings.

**Comment by jdimeo** [comment]
🎉 thank you! When will this be "live"? Does Tolgee.js release on the same schedule as Tolgee platform?

**Comment by stepan662** [comment]
Ah, sorry we didn't notify you. It is live. It should be enough to upgrade Tolgee SDK.
