### ISSUE TITLE
include tolgee-ui just in certain modes

### ISSUE THREAD

**Issue by jmtt89** [tolgee/tolgee-js#3104]
Hi, 

I recently ran webpack-bundle-analyzer with angular build stats and notice that tolgee-ui is a very very huge dependency, i follow the current instructions 

```
import {NgxTolgeeModule} from "@tolgee/ngx";
import {UI} from "@tolgee/ui";
import {NgModule} from '@angular/core';
import { environment } from '../environments/environment';


@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...,
    NgxTolgeeModule.forRoot({
      apiUrl: environment.tolgeeApiUrl,
      apiKey: environment.tolgeeApiKey,
      ui: environment.tolgeeApiKey ? UI : undefined
    }),
...,
],
...,
})
export class A
```

and is included anyways in production build

In Production environment tolgeeApiKey is undefined

```
export const environment = {
  tolgeeApiKey: undefined,
}
```

Do you have a way to only include this dependency in development mode? 

Currently the only solution i found is to comment just before `ng build`

**Comment by JanCizmar** [comment]
Hi there. You can import the UI conditionally using require: 

https://github.com/tolgee/ngx-example/blob/main/projects/sampleapp/src/app/app-routing.module.ts

But it's actually outdated in the docs, I'll fix this. Thanks!

**Comment by jmtt89** [comment]
Thanks, I will do it!
