### ISSUE TITLE
React Native: window.addEventListener is not a function

### ISSUE THREAD

**Issue by tranbathanhtung** [tolgee/tolgee-js#3105]
![Screen Shot 2022-10-12 at 10 33 31](https://user-images.githubusercontent.com/26837622/195243745-61267ee8-38ad-46ac-b292-ed6e815f4033.png)

I'm using tolgee for both web and react-native ... but seems like It throws an error on mobile... It does not crash the app but we use sentry to track errors and It is very annoying... Can tolgee provide a version to check the window before init or provide a solution for this case?

**Comment by JanCizmar** [comment]
Tolgee is not yet ready for React native. We are working on that. Stay tuned!

**Comment by stepan662** [comment]
React native is now tested, here is the docs: https://tolgee.io/js-sdk/integrations/react/react_native
