### ISSUE TITLE
Javascript exception on hover item with tolgee browser extension not applied

### ISSUE THREAD

**Issue by philippjenni** [tolgee/tolgee-js#3107]
If you hover over an element with the "alt" key pressed, Javascript enabled for InContext translation, and the Tolgee extensions in Chrome set to "applied". Each hover calls a Javascript exception in MouseEventHandler.ts.

```
helpers.ts:111 Uncaught TypeError: e._tolgee.highlight is not a function
    at t.highlight (MouseEventHandler.ts:51:20)
    at t.updateHighlight (MouseEventHandler.ts:76:10)
    at t.updateCursorPosition (MouseEventHandler.ts:81:10)
    at onMouseMove (MouseEventHandler.ts:91:10)
    at sentryWrapped (helpers.ts:87:17)
```

The problem is that the object `ElementWithMeta` has in this case not method `highlight()` and `unhighligth()`. This sould be checked in `highlight` and `unhighlight` methods of `MouseEventHandler.ts`

**Comment by JanCizmar** [comment]
Can you please share some example of your setup? Preferably on StackBlitz or similar? This shouldn't happen, since all elements with `_tolgee` atribute should have this method.

**Comment by philippjenni** [comment]
@JanCizmar Problem is solved with latest Version of SDK and Chrome Plugin

**Comment by JanCizmar** [comment]
Great!
