### ISSUE TITLE
Prerelease 5 usage 

### ISSUE THREAD

**Issue by Imjamper** [tolgee/tolgee-js#3126]
Hi, thanks for tolgee, brilliant solution, can you provide sample code of initialization Tolgee instance in 5 prerelease version. Thanks

**Comment by JanCizmar** [comment]
Hello! Sorry, we haven't released the new docs yet. Here is the preview: https://deploy-preview-313--tolgee-docs-preview.netlify.app/js-sdk/5.0.0-alpha.1/
