### ISSUE TITLE
Error using Vite 4.0.0 __vite_ssr_import_1__.Tolgee is not a function

### ISSUE THREAD

**Issue by v-rogg** [tolgee/tolgee-js#3142]
Using Vite 4.0.0 is results in the error `__vite_ssr_import_1__.Tolgee is not a function` when using sveltekit

## Steps to reproduce

1. Download the latest [tolgee svelte example](https://github.com/tolgee/svelte-example)
2. Update vite to version 4.0.0 (and optionally sveltekit to version 1.0.0 (release not next))

Error thrown:
```
__vite_ssr_import_1__.Tolgee is not a function
TypeError: __vite_ssr_import_1__.Tolgee is not a function
    at +layout.svelte:5:17```

**Comment by stepan662** [comment]
Hey, I was testing this, but I was not able to fix this. It seems like some bug in vite/svelte kit in dev mode, because when you build it for production it works fine.

The only fix I was able to do was to prevent tolgee usage on SSR:

```svelte
<script lang="ts">
  import { TolgeeProvider, Tolgee, DevTools, BackendFetch, type TolgeeInstance } from '@tolgee/svelte';
  import { FormatIcu } from '@tolgee/format-icu'
  import { onMount } from 'svelte';

  let tolgee: TolgeeInstance

  onMount(() => {
    tolgee = Tolgee()
      .use(DevTools())
      .use(FormatIcu())
      .use(BackendFetch())
      .init({
        apiUrl: import.meta.env.VITE_TOLGEE_API_URL,
        apiKey: import.meta.env.VITE_TOLGEE_API_KEY,
        language: 'en',
        availableLanguages: ['en', 'de', 'cs', 'fr'],
      }); 
  })
</script>

{#if tolgee}
<TolgeeProvider tolgee={tolgee}>
  <div slot="fallback">Loading...</div>
  <slot />
</TolgeeProvider>
{/if}
```

**Comment by ecstrema** [comment]
Hmm weird bug. I got the same, and wrapping it in `onMount` adds noticeable delay.

**Comment by ecstrema** [comment]
Hmmm, It doesn't seem fixed on my end. I just update `@tolgee/svelte` to 5.0.2 and I'm still getting that same error.
