### ISSUE TITLE
Allow functions as static data

### ISSUE THREAD

**Issue by ecstrema** [tolgee/tolgee-js#3144]
The only missing thing to have precompiled translations is for static data to accept a function, like this:

```ts
staticData: {
  en: {
    key_for_function: ({name}) => `Hello ${name}!`,
    key_for_string: "This is default",
  },
},
```

This probably means changing a few things in the translation core, like adding

```ts
if (typeof value === "function")
	return value()
return value
```

And changing the cache to something that says whether or not the key is a function, and then calls `new Function` with that.

However, it has the benefits of 
	- smaller download size
	- smaller execution footprint (no need for `formatSimple`, or even `formatICU`)

The backend could also provide precompiled functions instead of strings-to-be-formatted.

As for the actual transpilation to functions, a few solutions exist, the most popular being the [messageformat-cli](https://www.npmjs.com/package/messageformat-cli).

Cheers for the incredible work

**Comment by JanCizmar** [comment]
This would probably need
- Allow providing a function inside static data
- Allow providing JS files as translation data (so it doesn't have to be hardcoded in the code)
- Add typescript support, so it allows type checking in the code
- Update Tolgee CLI to use [messageformat-cli](https://www.npmjs.com/package/messageformat-cli) to generate such files. 

But it seems doable!

**Comment by ecstrema** [comment]
I was thinking about it, and actually, for now, juste acception functions inside the `t` function would do most of the job. 

I just don't know if this should be behind a feature flag, like

```ts
tolgee.use(formatFunction) // instead of formatSimple or formatICU
```

**Comment by JanCizmar** [comment]
Hello! I have been checking again on this and I don't this this is not possible while keeping Tolgee aligned with out vision of unifying the localization by using strong ICU message format.  

I know that this feature might look beneficial for JS devs, but it's out of scope for Tolgee as platform independent product.
