### ISSUE TITLE
Language selection is not saved locally 

### ISSUE THREAD

**Issue by thran** [tolgee/tolgee-js#3147]
I am using  @tolgee/ngx@5.0.1 and when `translateService.changeLanguage` is called language is switched but selection is not saved. After page reload I get default language. Local storage has no record from tolgee.

My provider:
```
{
    provide: TOLGEE_INSTANCE,
    useFactory: () => {
        return Tolgee()
            .use(DevTools())
            .use(FormatSimple())
            .init({
                defaultLanguage: 'en',
                availableLanguages: ['en', 'cs'],
                apiUrl: environment.tolgeeApiUrl,
                apiKey: environment.tolgeeApiKey,
                staticData: {
                    en: () => import('../assets/i18n/en.json'),
                    cs: () => import('../assets/i18n/cs.json'),
                }
            });
    },
}
```

**Comment by stepan662** [comment]
Hello, there is a plugin for that https://tolgee.io/js-sdk/api/web_package/plugins#languagestorage

**Comment by thran** [comment]
Thanks, good to know.
A note [here](https://tolgee.io/js-sdk/switching_language) and [here](https://tolgee.io/js-sdk/integrations/angular/switching-language) would be nice.

**Comment by JanCizmar** [comment]
You're right. Let mi fix that.
