### ISSUE TITLE
Using observerType: invisible fails in nextjs app with react-i18next in SSR

### ISSUE THREAD

**Issue by wodka** [tolgee/tolgee-js#3156]
Code Sandbox: https://codesandbox.io/p/sandbox/confident-montalcini-neskw6

![image](https://user-images.githubusercontent.com/385731/217910287-5353bdc2-132f-4bc2-8ec6-1b35c93e1c48.png)

-> it is actually a hydration error but breaks during rendering.

changing observerType from invisibe (default) to text shows again the actual error

(error came up in https://github.com/tolgee/tolgee-js/issues/3106 for me)

**Comment by stepan662** [comment]
Hey, the invisible observer is not designed to run on the server. I'll think about nicer solution, but now I was able to make it work by excluding `DevTools` during the initialization and adding them only on the client after initial render.

```js
// i18n.js

const tolgee = Tolgee()
  .use(I18nextPlugin())
  .use(FormatSimple())
  .init({
    // for production
    staticData: {
      de: {
        hello: "Hello World!!",
      },
    },
  });

withTolgee(i18n, tolgee)
  .use(detector)
  .use(ICU)
  .use(initReactI18next)
  .init({
    lng: "de",
    supportedLngs: ["de"],
  });

export default i18n;
```

```js
// _app.js

import { Suspense, useEffect } from "react";
import { withSSR } from "react-i18next";
import { DevTools } from "@tolgee/i18next";
import i18n from "../i18n";

export default withSSR()(({ Component, pageProps, ...other }) => {
  useEffect(() => {
    // delay the re-render, so next is not complaining about server not matching the client
    setTimeout(() => {
      i18n.tolgee.addPlugin(DevTools());
    }, 100);
  }, []);

  return (
    <Suspense fallback={<div>Loading...</div>}>
      <Component {...pageProps} />
    </Suspense>
  );
});
```

It's a similar approach to our integration example where the `tolgee.run` is moved to `useEffect`. Here it's called directly in the i18next init method, but we can delay the addition of `DevTools`.
