### ISSUE TITLE
The observer looks recursive

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-js#3164]
When I click any element on the page, it hangs (or it is consuming excessive amount of time):

![image](https://user-images.githubusercontent.com/2220320/220816904-053bf08e-2182-4e40-b770-00f1c87fd1c8.png)

**Comment by stepan662** [comment]
Hey, can you give me a means to replicate this?

**Comment by wfjsw** [comment]
It would require Python 3.10.6 ~ 3.10.9

```bash
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
cd stable-diffusion-webui
python -m venv venv
. venv/bin/activate
```

Replace `javascript/localization.js` with https://gist.github.com/wfjsw/672ecb68e231e8f579327d0fc5d34c35

```bash
python launch.py --ui-debug-mode
```

Then activate the In-Context tools with Tolgee Tools plugin.

**Comment by stepan662** [comment]
Hey, sorry, I'm not able to make your repo work. I would need something like minimal example.

**Comment by wfjsw** [comment]
https://colab.research.google.com/drive/1amhXOHKfHQx7gopIbVYUjeHDkmVmqbsQ?usp=sharing

Here is a minimal example that somehow reflects the complex situation that I'm facing.

I've somehow pinpointed the cause of the recurse which is Tolgee and my code meaninglessly fighting over `title` and `textContent` attributes when one side adds the invisible mark and the other side removes them. 

I then further modified the `getTranslation` to not returning anything when the translated text equals the key (which is the original text in this case). Now the page is free from freezing but I'm unable to receive any `MutationObserver` callbacks after the change.

Regarding the minimal example, it *sometimes* works - I can only get the highlights on the tab header. Since the original recursion issue is clear, feel free to close this if you are no longer interested in this.

**Comment by wfjsw** [comment]
I probably fixed it, though the thing it highlights still have some differences with the actual content and it is skipping something.
