### ISSUE TITLE
Quick translation is unable to find (some) existing key

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-js#3168]
![image](https://user-images.githubusercontent.com/2220320/221350053-facae389-0c2a-4280-b177-8b0e83282049.png)

![image](https://user-images.githubusercontent.com/2220320/221350062-c6539a6e-1a4d-4aaa-ba0c-726c9831a2ac.png)

![image](https://user-images.githubusercontent.com/2220320/221350072-a1d62939-f312-4b2e-a58b-6a9960b76752.png)

**Comment by wfjsw** [comment]
Probably a platform issue?

**Comment by JanCizmar** [comment]
Yep, it's an platform issue.

**Comment by JanCizmar** [comment]
It's definitely a bug. But I have to point out that we recommend agains using source strings as keys.

https://github.com/tolgee/tolgee-platform/issues/1585

**Comment by JanCizmar** [comment]
Fixed here: https://github.com/tolgee/tolgee-platform/pull/1586
