### ISSUE TITLE
Default namespace is not being adopted when using i18next

### ISSUE THREAD

**Issue by Vissie2** [tolgee/tolgee-js#3177]
When using [@tolgee/i18next](https://github.com/tolgee/tolgee-js/tree/main/packages/i18next) with the `InContextTools` plugin from [@tolgee/web](https://github.com/tolgee/tolgee-js/tree/main/packages/web) we noticed that whenever you update a translation with the In-context tool the namespace will be removed from the translation in Tolgee.

This happens when setting a default namespace for i18next and **not** setting the `ns` property in the `t()` function itself. I'm not quite sure if this is a bug or a feature which is not yet implemented but I think this should be default behavior.

[Reproduction](https://github.com/Vissie2/tolgee-i18next-vue)

**Comment by stepan662** [comment]
I'll prepare a fix for that

**Comment by Vissie2** [comment]
I forgot to mention that it could be due the usage of `i18next-vue` indeed. Thanks for the quick help!
