### ISSUE TITLE
Translations are not always displayed

### ISSUE THREAD

**Issue by evgen904** [tolgee/tolgee-js#3179]
if you update the page, then the translations are pulled up every other time,
the error occurs in the `tolgeeBackend` method when calling `read` `await tolgee.loadRecord`
please tell me how can I fix this? ))

**Comment by stepan662** [comment]
Hey, can you provide some example? I haven't seen this error.

**Comment by evgen904** [comment]
> Эй, можешь привести пример? Я не видел эту ошибку.

She only shows up once in a while ) http://joxi.ru/E2pVggeS75LRBr

**Comment by JanCizmar** [comment]
Hey! You have to provide more information about this and maybe also provide minimal reproducible example. Thanks. :)

**Comment by evgen904** [comment]
The problem occurs only when working with localhost, when the extension for chrome
https://chrome.google.com/webstore/detail/tolgee-tools/hacnbapajkkfohnonhbmegojnddagfnj
and it has the option Applied.
In principle, it is not critical, you can close the topic)
