### ISSUE TITLE
Feature Request: Command Line Option to list/create missing entries

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-js#3192]
Hey everyone,
is there a plan / a current option to check for / create missing entries within the project via command-line or "on the fly"?

**Comment by JanCizmar** [comment]
That's what the CLI already does.

https://tolgee.io/tolgee-cli

**Comment by paulwer** [comment]
@JanCizmar sorry to bother you.
$t() as function within tolge/vue is ignored and therefore these entries are makred as deleteable and or new entries does not get notified.
Is there an option to include this function?

**Comment by JanCizmar** [comment]
Unfortunately, the CLI doesn't support Vue.js yet. But you might be open to contribute with Vue extractor! 🚀

**Comment by paulwer** [comment]
is there a way to put this feature on your schedule?
