### ISSUE TITLE
Translation concept

### ISSUE THREAD

**Issue by ecstrema** [tolgee/tolgee-js#3206]
I had some time, so I designed my dream InContext translation chooser: here's the [CodePen](https://codepen.io/marr11317/pen/ZEqZaeL)

Throw your comments!

**Comment by ecstrema** [comment]
Edit: updated the [link](https://codepen.io/marr11317/pen/ZEqZaeL)

**Comment by stepan662** [comment]
Hey, this looks like an cool idea. I understand that you want to highlight all translations which are on the page when user hits the alt click. But I'm not sure if you also suggest some changes with the events.

I've already played a bit with the events in current implementation. I've found out that you can block/capture events on document level and you don't have to set it on all elements individually. Then there is also handy `elementFromPoint` api, which allows us to find out which element was clicked without the event actually ever arriving to it. The resulting effect makes the page `freeze` so e.g. interactive tooltips stay visible. It doesn't work perfectly (e.g. css still reacts to mouse movements), but I found it pretty good.

https://github.com/tolgee/tolgee-js/blob/main/packages/web/src/observers/general/MouseEventHandler.ts

**Comment by ecstrema** [comment]
I find a few problems with the existing implementation: 

1) The application often gets stuck in translation mode. For example, just press alt-tab to switch window. When you come back, you still can't click on anything, and the app is waiting for you to choose a translation, even though you're not pressing alt anymore.
2) Since you only see translatable text when you hover it, it's not easy to spot if you forgot to make something translatable.
3) In translation mode, you have no indicator of what you need to do. For new users, it can be weird. You don't immediately realize that if you click on a translated string, a popup will open, since really nothing has changed in the UI until you start hovering things.
4) The red box is very visible, but not very sympathetic to the eyes, and may be invisible on a red background (although that should rarely happen:).

**Comment by ecstrema** [comment]
I find a few problems with the existing implementation: 

1) The application often gets stuck in translation mode. For example, just press alt-tab to switch window. When you come back, you still can't click on anything, and the app is waiting for you to choose a translation, even though you're not pressing alt anymore.
2) Since you only see translatable text when you hover it, it's not easy to spot if you forgot to make something translatable.
3) In translation mode, you have no indicator of what you need to do. For new users, it can be weird. You don't immediately realize that if you click on a translated string, a popup will open, since really nothing has changed in the UI until you start hovering things.
4) The red box is very visible, but not very sympathic to the eyes

**Comment by ecstrema** [comment]
> css still reacts to mouse movements

That's also the advantage of using the "highlight all" approach. Even if the element disappears, its highlighter is still there, and so the element can still be clicked, until alt is released. In other words, pressing alt creates a snapshot of the page, and you can translate everything that was visible at that moment.

**Comment by stepan662** [comment]
I'm closing this for low interest from userbase. But feel free to comment on these ideas here and we can reopen this.
