### ISSUE TITLE
Tolgee with Next.JS new pages and layout structure

### ISSUE THREAD

**Issue by mleimer** [tolgee/tolgee-js#3228]
The example listed on [https://tolgee.io/js-sdk/integrations/react/ssr/next is using the old ](https://tolgee.io/js-sdk/integrations/react/ssr/next) is based on the old app-folder structure and not compatible with the new pages and layout structure as defined here: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts

In fact, it is not possible to read from `next/router` in the `src/app/layout.tsx` component, as that `RootLayout` is a server component. 
How to use TolgeeProvider with server components? If this is not intended, what is the suggested approach how to integrate Tolgee with Next.JS new pages and layout structure?

**Comment by mleimer** [comment]
Note: Using a concept like documented in https://tolgee.io/js-sdk/integrations/react/ssr/ where the language is not read from router doesn't work either, because this will cause another error:

```
./node_modules\@tolgee\react\dist\tolgee-react.esm.mjs
ReactServerComponentsError:

You're importing a component that needs useRef. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[C:\Users\marti\IdeaProjects\tolgee-taiwlind-material\tolgee-tailwind-material\node_modules\@tolgee\react\dist\tolgee-react.esm.mjs:1:1]
 1 | import React, { useState, useEffect, Suspense, useContext, useCallback, useRef, useMemo } from 'react';
   :                                                                         ^^^^^^
 2 | import { getFallback, getFallbackArray, getTranslateProps } from '@tolgee/web';
 3 | export * from '@tolgee/web';
   `----

Maybe one of these should be marked as a client entry with "use client":
  ./node_modules\@tolgee\react\dist\tolgee-react.esm.mjs
  ./src\app\layout.tsx
```

**Comment by stepan662** [comment]
Hey, actually I've been looking at this last week. The problem is that the server components API is still quite experimental, however I'll probably at least write article about how it can be integrated with Tolgee. Later when the API is stable, we'll probably create a separate package for next.js.

**Comment by stepan662** [comment]
I've created an article and example app for next.js app router https://tolgee.io/blog/how-to-setup-tolgee-with-nextjs-app-router

**Comment by mleimer** [comment]
Thank you very much for your initiative and bringing up a way how we can integrate Tolgee at this early stage with RSC. Looking forward to see what the future brings and whether the limitations you mentioned can be overcome at some point. Thanks a lot!
