### ISSUE TITLE
Component can unmount while fetch request is running and cause react error

### ISSUE THREAD

**Issue by stepan662** [tolgee/tolgee-js#325]
https://github.com/tolgee/tolgee-js/blob/ee5ae8305b7f2cd45680264aba1af6175194599e/packages/react/src/useTranslate.ts#L69

![Snímek obrazovky 2021-07-29 v 14 35 25](https://user-images.githubusercontent.com/8831144/127492664-c19bee53-57c7-4bf8-9006-49542246feab.png)

At least I think something like that is happening.

**Comment by JanCizmar** [comment]
Should be fixed with

https://github.com/tolgee/tolgee-js/pull/578
