### ISSUE TITLE
Tags interpolation not working with numbers?

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-js#3265]
Trying to interpolate the `<1>` tag here:

```json
"account.apiTokens.deleteConfirmationMessage": "The token <1>tokenName</1> will be permanently revoked, are you sure you want to continue?",
```

```tsx
<T
  keyName="account.apiTokens.deleteConfirmationMessage"
  params={{
    1: <strong>My token</strong>,
  }}
/>;
```

This displays "invalid". Any reason why numbers are not accepted here? :)

**Comment by stepan662** [comment]
We are using format js for the tags interpolation, but it seems like it's not able to handle numbers.
https://formatjs.io/docs/intl-messageformat#rich-text-support

We already have an issue with self-closing tags, so we'll probably release a separate tag parser to solve this.
