### ISSUE TITLE
i18n Ally compatibility

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-js#3266]
Is there any plan to make the SDK compatible with i18n-ally? Or maybe there's already a framework implementation that is close enough to the tolgee syntax?

I've been trying with `react-i18next` framework settings. It works fine for `t('...')` but not for `<T keyName="...">`

**Comment by stepan662** [comment]
We have a plan to make our own code editors plugins, since our flow is a bit different with context gathering and so on.
