### ISSUE TITLE
Tolgee plugin in chrome does not work for strings located in shadow dom

### ISSUE THREAD

**Issue by zeldigas** [tolgee/tolgee-js#3273]
I'm testing tolgee on react app that renders itself in shadow dom. The problem I'm currently facing - integration with Tolgee chrome plugin does not work - I press alt, hover over string that needs to be translated but nothing happens.

I tried to remove shadow dom and then it works as expected. Is there any specifics to configure tolgee for such scenario or it is some sort of bug?

Some details:

Tolgee version:
```
"@tolgee/format-icu": "5.14.0",
"@tolgee/react": "5.13.3",
```

Not sure if it's important, but here's the code that prepares shadow dom:
```typescript
import { createRoot } from 'react-dom/client';

const createShadowRoot = (root: Element): HTMLDivElement => {
  const shadowRoot = root.attachShadow({ mode: 'open' });

  const style = document.createElement('style');
  style.textContent = `
    #app-shadow {
      all: initial;
    }
  `;
  shadowRoot.appendChild(style);
  const appContainer = document.createElement('div');
  appContainer.id = `app-shadow`;
  shadowRoot.appendChild(appContainer);
  return appContainer;
}

//during app init:

const reactAppRoot = createRoot(createShadowRoot(.....div element where to create shado is passed here....))
reactAppRoot.render(<MyApp/>)
```

**Comment by stepan662** [comment]
Hey, there is a `targetElement` property, which determins where should the observer look for translations, you can set it up to your container in shadow dom and looks like it works 🙂 At least I didn't find any issue with it.

```
Tolgee()
  ...
  .init({
    observerOptions: {
      targetElement: container,
    },
    ...
  });
```

**Comment by zeldigas** [comment]
@stepan662 thank you for the tip! I tried it with mixed success.

If tolgee is initialized with api key - then highlight of i18n keys works and popup with inline translations/screenshots works as well.

But if I rely on browser plugin, I can see only highlighted text - click on it does not show this inline translation modal window.

If I'll not find solution with real app codebase, I'll try to do some sample app to reproduce problem.

**Comment by stepan662** [comment]
I've tested it on this example app (branch: `stepangranat/shadow-dom-example`) and it seems to work regardless I use plugin or dev mode.

https://github.com/tolgee/react-example/tree/stepangranat/shadow-dom-example

**Comment by zeldigas** [comment]
@stepan662  sorry for delay. Indeed it works once provided target element. In my case there were 2 separate shadow dom locations, that required some coordination in initialization of tolgee (2 instances with different taget elemenents). But it works.
