### ISSUE TITLE
[vite] Error when evaluating SSR module, failed to import "@tolgee/format-icu"

### ISSUE THREAD

**Issue by hasagen** [tolgee/tolgee-js#3275]
Hi, guys!
I have such an issue with vite and tolgee packages (@lolgee/react and @tolgee/format-icu in my case)

<img width="1255" alt="image" src="https://github.com/tolgee/tolgee-js/assets/81259327/a132a390-8660-495c-b3da-2af5c603a576">

So I have to create patches like this to make Tolgee work correctly.
<img width="572" alt="image" src="https://github.com/tolgee/tolgee-js/assets/81259327/e5d6261b-280e-455d-8145-a18827cbb2bd">

So i've change .js to .mjs format.
Please check

**Comment by stepan662** [comment]
Hey, how do I replicate your setup? (please include node and VITE versions).

**Comment by hasagen** [comment]
of course, node -v 18.12.1 + vite 4.5.0

**Comment by stepan662** [comment]
And how did you setup the SSR, I see there are multiple ways how to create a vite project with SSR, as the native implementation is very bare-bone.

**Comment by hasagen** [comment]
You're right, I actually didn't think that SSR realization could be the reason.
Anyway, I've checked prerelease and the problem solved. Thank you very much!
