### ISSUE TITLE
Screenshots taken may not work

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-js#3295]
hey everyone,
when taking screenshots from the ui, the modal is hidden and reapprears, but no screenshot was taken.
Console Output:
`Didn't recieve TOLGEE_SCREENSHOT_TAKEN in time.` useGalery.ts:108

Anything I can do?

**Comment by stepan662** [comment]
Hmm, weird, do you have Tolgee Tools chrome plugin installed?

**Comment by stepan662** [comment]
Chrome is restricting plugins a bit more, so maybe it was somehow connected. We've needed to rewrite it a bit recently, so maybe the old version is not working properly already.

**Comment by paulwer** [comment]
after refreshing the page like twice, it doesnt get reconized again :(

**Comment by stepan662** [comment]
Hmm, I haven't tested it in Edge before. But it seems working even after multiple refreshes. Do you have some reliable way to reproduce? Also you are using windows or mac?

**Comment by paulwer** [comment]
I am using windows. Sadly no I cannot give a reliable way to reproduce.
I also discovered, that when the screenshot was taken and is display in the bottom, it results in a img-not loaded item, which also cannot be uploaded to tolgee.

![image](https://github.com/tolgee/tolgee-js/assets/52678724/0a28ebd9-6c80-4a4e-8830-c54b7a09de84)

**Comment by stepan662** [comment]
What do you mean by "that when the screenshot was taken and is display in the bottom"?

**Comment by paulwer** [comment]
when the screenshot was taken it would be shown in the modal at the end in section screenshots, before saving it.
By clicking on it, it would be displayed as above. (when not the error from above was in output => Didn't recieve TOLGEE_SCREENSHOT_TAKEN in time. useGalery.ts:108)

**Comment by stepan662** [comment]
Hmm, I'd need some way how to replicate this error. I'll try it out on windows in edge, but without replication, it's really hard to do anything about this.

**Comment by paulwer** [comment]
if you want, we could meet up, if you want me to show you our setup. if that helps.

Could this anything have to do with vite, because we use this?

What do you need from me?

**Comment by stepan662** [comment]
I'll write you on community slack.
