### ISSUE TITLE
Pulling translations by specific datetime

### ISSUE THREAD

**Issue by amir2mi** [tolgee/tolgee-js#3301]
I've read the API documents and Tolgee CLI, but there was no option to get translations providing a date range, like a snapshot of all the translations at that specific datetime.

### Use Case
I use the Tolgee CLI to pull the translations at build time. It means if I rebuild the last week build, it probably will have some missing or changed translations, because the pulled translations are always the last version of changes.

### A new feature?
I see that the Tolgee has a great history per translation key, so I was wondering if it is possible to pull translations like this:

```bash
tolgee pull ./public/i18n --api-key=my_api_key --until="2024-01-02T11:00:00.137Z"
```

**Comment by JanCizmar** [comment]
Hi! Thanks for the query. This is more like a feature request to https://github.com/tolgee/tolgee-platform 

However, the simpler way how to solve this would be to just don't delete keys when you know you are using them in other builds. Retrieving previous versions would be possible, but not trivial, so I don't think we can get that implemented soon.
