### ISSUE TITLE
Invisible chars added to string loaded with `t` function

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-js#3302]
My `en.json` file contains this key:

```json
"templates.modal.marketing.leadGeneration.name": "Lead Generation",
```

I actually found out that invisible caracters are added to the string:

```tsx
const { t } = useTranslate()
console.log(
    t('templates.modal.marketing.leadGeneration.name'),
    Object.entries(t('templates.modal.marketing.leadGeneration.name')),
    t('templates.modal.marketing.leadGeneration.name') === "Lead Generation" // output: false
)
```

It prints 24 entries instead of 15.

<img width="1465" alt="CleanShot 2024-01-23 at 19 27 03@2x" src="https://github.com/tolgee/tolgee-js/assets/16015833/aa312b80-d268-4c32-b7dc-9d375babf246">

Do you manage to reproduce that? 🤔

**Comment by stepan662** [comment]
Hey, this seems like a correct behavior. If you use `DevTools`, we add invisible characters to each rendered translation, so it can be detected in the dom and registered for in-context translating. You can opt-out from this by doing
```
t('key', { noWrap: true })
```

**Comment by baptisteArno** [comment]
Alright, it makes sense now :)
