### ISSUE TITLE
Some localized strings are not shown properly on production, but they look just fine locally 

### ISSUE THREAD

**Issue by vadimkalaida** [tolgee/tolgee-js#3309]
Recently, we faced a problem: some of our strings did not look like they had to. 

This is what it looks like on production:
<img width="275" alt="Screenshot 2024-02-06 at 11 23 05" src="https://github.com/tolgee/tolgee-platform/assets/44207160/df32b5f7-cd9a-4e0b-866c-90003e692dd3">

This is what it has to be (we have it locally):
<img width="270" alt="Screenshot 2024-02-06 at 11 24 12" src="https://github.com/tolgee/tolgee-platform/assets/44207160/99a91053-fc56-46e8-9c7a-ab5e948ed433">

As you can see, only some of them are not displayed correctly while others are just fine. Honestly, I have no idea why it looks like this

**Comment by vadimkalaida** [comment]
Here is some demonstration:
https://github.com/tolgee/tolgee-js/assets/44207160/d6fabf88-50c5-48a6-a067-5ee9a6291c86

**Comment by vadimkalaida** [comment]
Here is some demonstration:

https://github.com/tolgee/tolgee-js/assets/44207160/2fcb4ea8-254c-4125-8f7a-311eac964d89

**Comment by JanCizmar** [comment]
Are you using Tolgee Cloud or Self-hosted version? I guess this might happen due to using structured export. How are you getting the translations to production?

**Comment by vadimkalaida** [comment]
We are using Tolgee Cloud, but we are planning to move to Self-hosted version in the near future

**Comment by JanCizmar** [comment]
Can you please share how exactly you're exporting the data in the build process, including the code?

**Comment by vadimkalaida** [comment]
During the building process of production the translations are fetched using this command: 
`"cd public/i18n && curl https://app.tolgee.io/v2/projects/export -H \"X-API-Key: ${VITE_TOLGEE_API_KEY}\" | jar xv && cd ../.."`

**Comment by stepan662** [comment]
Hey, could you also share the Tolgee initialization?

**Comment by stepan662** [comment]
Hey, could you also share the Tolgee initialization?

**Comment by vadimkalaida** [comment]
> Hey, could you also share the Tolgee initialization?

```
const tolgee = Tolgee()
  .use(DevTools())
  .use(FormatIcu())
  .use(BackendFetch())
  .init({
    language: getLanguage(),
    fallbackLanguage: "en",
    apiUrl: import.meta.env.VITE_TOLGEE_API_URL,
    apiKey: import.meta.env.VITE_TOLGEE_API_KEY,
  })
```

**Comment by stepan662** [comment]
Hmm, that looks OK 🙁 One other thing you can debug is to check how is the tolgee cache looking after you load the data. If you add this piece, it should dump the cache content to the console, so we can check if anything is wrong there.

```ts
tolgee.on('initialLoad', () => {
  console.log(tolgee.getAllRecords());
});
```

**Comment by ZuzanaOdstrcilova** [comment]
Any updates @vadimkalaida?

**Comment by vadimkalaida** [comment]
> Any updates @vadimkalaida?

Just moved from hosted Tolgee, and everything seems fine now

**Comment by JanCizmar** [comment]
OK, thanks for reporting. :)
