### ISSUE TITLE
Dev tools error handling

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-js#3329]
In past month users repeatedly reported 4xx error being printed in the SDKs. While some of these are backend issues, we still need to provide better user experience when the API key is missing or when API key scope is missing.

Recently I've added missing scope as a parameter when responding with 403, so we can tell the user exactly which scopes they need to add to proceed. 

![image](https://github.com/tolgee/tolgee-js/assets/18496315/407f9011-9a46-49f6-b843-00f2c006049f)

- [ ] Enhance the UI of the error.  
  - [ ] Because the meaning of 4xx errors is that user did something wrong, i don't think the number error is valuable information for them.
  - [ ] The red text feels scary to me
  - [ ] Tell users exactly how to resolve the error
    - [ ] When the API key is missing, we should tell them that API key is missing and they should add it in the code or via the chrome plugin with link to docs (not sure if we recognize which method they use)
    - [ ] When there is missing scope, we should tell them to add it and how

**Comment by ZuzanaOdstrcilova** [comment]
Here is the design for errors:
https://www.figma.com/file/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?type=design&node-id=1536%3A5540&mode=design&t=dFCUMmw86Htmaxn2-1

![Image](https://github.com/tolgee/tolgee-js/assets/99287646/0bd656d6-0c5f-4c92-ab2a-f82ba16f3806)
