### ISSUE TITLE
Type error for tag interpolation when using useTranslate hook

### ISSUE THREAD

**Issue by Yureien** [tolgee/tolgee-js#3337]
This is what is stated in the documentation, and works successfully:

```javascript
const Component = () => {
  return (
    <div>
      <T
        keyName="translation_key"
        params={{ i: <i /> }}
        defaultValue="This is <i>formatted</i>"
      />
    </div>
  );
};
```

However, this gives a type error with the equivalent `useTranslate` hook:

```javascript
const { t } = useTranslate();

const result = t("translation_key", "This is <i>formatted</i>", { i: <i /> });
```

It seems that the `DefaultParamType` does not accept `JSX.Element` types:

```typescript
export type DefaultParamType = string | number | bigint | Date;
```

**Comment by stepan662** [comment]
Hey, this is intentional, as the `t` function is supposed to always return simple string. In contrast, `T` component always returns JSX.Element, so the intention is to express different usecases for these two primitives.
