### ISSUE TITLE
Add an option to prevent BackendFetch from sending X-Tolgee-Sdk-Type and X-Tolgee-SDK-Version

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-js#3346]
#3224 added headers that is sent on `BackendFetch` causes an unwanted side effect that the fetch now requires CORS preflight, which is not supported on some static host.

**Comment by stepan662** [comment]
Hmm, yes you are right, it's actually quite pointless on BackendFetch, it's only there because it's using the same fetch function. I'll look at it.
