### ISSUE TITLE
[tolgee-vue] Translation Text Disappears After Refreshing the Page with Specific Key Usage

### ISSUE THREAD

**Issue by firmianaQ** [tolgee/tolgee-js#3350]
## Description:

I have a TypeScript file with the following content:
```typescript
export const label = { name: toggle.t('label.name') };
```
When I first enter a page that does not use this key, and then navigate to a page that does use this key, the translation text is displayed correctly. However, once I refresh the page, the translation text no longer appears.

## Steps to Reproduce:

1. Navigate to a page that does not use the key 'label.name'.
2. Proceed to a page that utilizes the key 'label.name'.
3. Observe that the translation text is displayed as expected.
4. Refresh the page.
5. Notice that the translation text is missing.

**Comment by stepan662** [comment]
Hey, the error comes probably from the fact that you are accessing the translations before they are loaded. You are using tolgee instance directly, which is problematic, because you don't know if the translations were loaded or not.

I'd recommend to use this with e.g. composition API:

```
function useLabels() {
  const { t } = useTranslate()
  return {
    name: t.value('label.name')
  }
}
```

Now it's hooked into vue lifecycle, so it should access the translations only when they are loaded.

**Comment by firmianaQ** [comment]
My solution is not to use `VueTolgee`


`tolgee.ts`
```typescript
import { DevTools, FormatSimple, LanguageDetector, LanguageStorage, Tolgee } from '@tolgee/vue';

export const tolgee = Tolgee()
  .use(DevTools())
  .use(LanguageDetector())
  .use(LanguageStorage())
  .use(FormatSimple())
  .init({
 ...
  });
  
export const setupTolgee = async () => {
  await tolgee.run();
}
```

`main.ts`
```typescript
...
import { setupTolgee  } from './tolgee ';
...
await setupTolgee();

app.mount('#app');
```

`App.vue`
```vue
<script setup lang="ts">
import { TolgeeProvider } from '@tolgee/vue';
import { tolgee} from './tolgee';
</script>

<template>
  <tolgee-provider :tolgee="tolgee">
    <App/>
  </tolgee-provider>
</template>

<style lang="scss">
</style>

```

**Comment by firmianaQ** [comment]
> Hey, the error comes probably from the fact that you are accessing the translations before they are loaded. You are using tolgee instance directly, which is problematic, because you don't know if the translations were loaded or not.
> 
> I'd recommend to use this with e.g. composition API:
> 
> ```
> function useLabels() {
>   const { t } = useTranslate()
>   return {
>     name: t.value('label.name')
>   }
> }
> ```
> 
> Now it's hooked into vue lifecycle, so it should access the translations only when they are loaded.

That's correct, but there are too many such usages in the existing code, making it not easy to change
