### ISSUE TITLE
'Tolgee' is not exported from '@tolgee/react'

### ISSUE THREAD

**Issue by MikaCinc** [tolgee/tolgee-js#3354]
We've been following [this guide](https://tolgee.io/js-sdk/integrations/react/next/app-router) for Tolgee in Next with the app router a couple of months ago but we always had issues when the language is changed using lang toggle. The currently rendered page translates to the new language but going to some other page there is the chance it is still shown with the previously selected language... 

Anyway, we see that the guide has been updated a bit with the new versions on `tolgee/web`, `tolgee/react` and `next-intl`, so we tried updating the libs and changing the latest stuff from the guide hoping it will fix our previous errors. 
This new error happens on versions greater than:
```
"@tolgee/react": "^5.22.0",
"@tolgee/web": "^5.22.0",
```
It's present even on yesterday's latest version (`5.28.5`).

> ./tolgee/shared.ts
> Attempted import error: 'Tolgee' is not exported from '@tolgee/react' (imported as 'Tolgee').
> 
> Import trace for requested module:
> ./tolgee/shared.ts
> 
> ./tolgee/shared.ts
> Attempted import error: 'FormatSimple' is not exported from '@tolgee/react' (imported as 'FormatSimple').
> 
> Import trace for requested module:
> ./tolgee/shared.ts
> 
> ./tolgee/shared.ts
> Attempted import error: 'DevTools' is not exported from '@tolgee/react' (imported as 'DevTools').
> 
> Import trace for requested module:
> ./tolgee/shared.ts
>  ⚠ ./node_modules/@tolgee/react/dist/tolgee-react.esm.js
> Attempted import error: 'getFallbackArray' is not exported from '@tolgee/web' (imported as 'getFallbackArray').
> 
> Import trace for requested module:
> ./node_modules/@tolgee/react/dist/tolgee-react.esm.js
> ./tolgee/shared.ts
> 
> ./node_modules/@tolgee/react/dist/tolgee-react.esm.js
> Attempted import error: 'getTranslateProps' is not exported from '@tolgee/web' (imported as 'getTranslateProps').
> 
> Import trace for requested module:
> ./node_modules/@tolgee/react/dist/tolgee-react.esm.js
> ./tolgee/shared.ts

**Comment by stepan662** [comment]
Hey, we had this issue reported previously and users reported, that they were able to fix it either by upgrading next.js or tsconfig.json, so please try that. I would like to know what exactly is causing this, but I was not able to replicate.

**Comment by MikaCinc** [comment]
Updating next to 14.2.4 resolves the `'Tolgee' is not exported from '@tolgee/react'` issue. However, still when everything is upgraded to the latest versions and the files from [the guide](https://tolgee.io/js-sdk/integrations/react/next/app-router) updated too we have that tolgee language switch issue present. Should I create a new issue for that here?

Here are the current versions:
```
"@tolgee/react": "^5.28.5",
"@tolgee/web": "^5.28.5",
"next": "14.2.4",
"next-intl": "3.15.3"
```
