### ISSUE TITLE
NextJS mode: "export" can't get InContext tools working in PROD

### ISSUE THREAD

**Issue by i-love-code** [tolgee/tolgee-js#3360]
Can't seem to get DevTools or InContextTools to leverage the Chrome Extension when using `mode: "export"` with NextJS static generation.

Any tips?

**Comment by stepan662** [comment]
Hey, could you provide more details how to replicate this issue? Do you use app router with next-intl?

**Comment by i-love-code** [comment]
Sure, here's a repo with it replicated using your sample nextjs app.

When running with `npm run dev`, translations are wrapped and it works as expected: 
![image](https://github.com/user-attachments/assets/5eeeb6aa-9ae7-4811-96a3-696d21c758a2)

When run with `npm run build; npx serve@latest out` (how exported static nextjs apps are run locally), there is no wrapping / plugin cannot be used to translate.

**Comment by i-love-code** [comment]
Whoops, repo link: https://github.com/i-love-code/tolgee-export-devtools

**Comment by i-love-code** [comment]
As for your question, if you haven't seen it already, we are using next-intl but we aren't using the middleware, instead we're providing static export params and using `/<locale>` prefix to avoid paying for the server costs (able to host static if you don't use middleware to route locales)

**Comment by stepan662** [comment]
Ok, thanks for the example. I've tested your app and when I deploy it with `npx serve@latest out`, it works as expected - plugin detects tolgee on the page and I'm able to insert api key (in-context works).
![Snímek obrazovky 2024-08-08 v 9 18 23](https://github.com/user-attachments/assets/3bdf66e9-0346-4e11-9e89-f77748d8bc93)
![Snímek obrazovky 2024-08-08 v 9 18 30](https://github.com/user-attachments/assets/8c186dca-cef4-4e4f-8320-367091619237)

**Comment by i-love-code** [comment]
My apologies, I didn't make an accurate recreation. There's one other change, we use almost exclusively server-side translations and do not load the entire translation `i18n/<file>.json` dictionaries in the browser like the example does.

When I replicate the sample project, loading the static translation data, it's true that highlighting works, but the browser payload is almost ~8MB of just translations because next is hiding the entire 10,000+ translation over 3-4 namespace dataset for all translations with locale and fallback locale in the browser in javascript.

To avoid that, I was loading a blank/empty set of static data into the TolgeeNextProvider and only using server-side translations.

I made a branch, [no-client-i18n](https://github.com/i-love-code/tolgee-export-devtools/tree/no-client-i18n) that should replicate it.

All of the server-side translations work and show the translated content, but I can't hover and highlight them to edit. I was hoping it still let them pop up and be editable like it does in dev mode, even if they were server-side translation values.

https://share.ilovecode.dev/msedge_sGZOsvm1XK.mp4

This might be intended, I assume a workaround _could_ be to specifically pull out only the keys from the i18n files that I need for the individual page and provide the TolgeeNextProvider with only the very specific translations I wish to load into the client, but it would make for a lot of manual management of key names.

**Comment by stepan662** [comment]
I've tried the example, but it seems like there is no apiKey passed to tolgee.
You might try to override DevBackendPlugin to return undefined, so it wouldn't load anything from backend. Something like:

```
const tolgee = TolgeeBase()
  .use((tolgee, tools) => {
    tools.setDevBackend({
      async getRecord() {
        return undefined;
      },
    });
    return tolgee;
  })
  .init();
```

However, this can be used only with server components, if you'd try to use tolgee with client components, translations won't be there.

**Comment by i-love-code** [comment]
Maybe I'm not following -- I tried to put that into `tolgee/client.tsx` but it didn't seem to change anything, the server component translations still don't have InContext shown with alt+hover, only the client translations do.

https://github.com/i-love-code/tolgee-export-devtools/commit/0154ffe33b1319038a2e4f1f2a2929b877e55d25

**Comment by i-love-code** [comment]
And yeah -- I am basically looking for server-side translations only from the files in the i18n folder, not interested in client-side translations or having an apiKey on the client that eventually makes it's way to the user's browser for live reads, but still able to in-context use the Chrome extension to let editors alt+hover and edit translations in PROD.

**Comment by stepan662** [comment]
Hmm, I'm afraid that that is currently not quite possible. Plugin doesn't influence the backend so now you can't easily switch server rendered translations into development mode for updating the translations.

You could however, have a staging version, where the backend would be switched to development mode and ready for translators to change the translations there.

Try this example, it's tweaked, so it only loads translations on the server:
https://github.com/tolgee/next-app-example/tree/stepangranat/i-love-code-example

**Comment by i-love-code** [comment]
Ah that's unfortunate. Makes sense -- we can go the "staging running dev mode" route for our translators.

Thanks for your help diagnosing!
