### ISSUE TITLE
Enable tag filtering / mandatory tag for sharing project keys between platforms

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-js#3365]
According to this [discussion](https://github.com/tolgee/tolgee-platform/discussions/2436), when client uses single project for multiple platforms, they need a way how to fetch only keys for specific platform tag. e.g. `web`, `mobile`.

- [ ] Add `filterTag` to the global Tolgee instance configuration
- [ ] Prevent removing this tag in the Dev tools UI when creating or updating key
- [ ] Filter data by this tag in BackendFetch plugin

This task depends on the backend filter support: https://github.com/tolgee/tolgee-platform/issues/2453

**Comment by stepan662** [comment]
https://github.com/tolgee/tolgee-js/pull/3404
