### ISSUE TITLE
Next.js App Router integration: You haven't read the `locale` param that was passed to `getRequestConfig` and also haven't returned one from the function

### ISSUE THREAD

**Issue by empz** [tolgee/tolgee-js#3372]
Following the guide described here to integrate Tolgee JS SDK into a Next.js App router application:
https://tolgee.io/js-sdk/integrations/react/next/app-router

Results in the following log printed on the server on every request:
```
You haven't read the `locale` param that was passed to `getRequestConfig` and also haven't returned one from the function. This is likely an error, please ensure that you're consistently using a setup with or without i18n routing: https://next-intl-docs.vercel.app/docs/getting-started/app-router
``` 

Why does the integration guide doesn't follow the next-intl official docs?

From Tolgee integration guide:
![image](https://github.com/user-attachments/assets/52913a38-6d5b-46c6-bb0d-2e4dd9dc7d33)

From next-intl docs
![image](https://github.com/user-attachments/assets/fea42857-54c2-46e1-b071-1d5f52d4533e)

**Comment by stepan662** [comment]
Hey, we basically don't need this function at all. However since next-intl is now more strict about it's usage, I'll updated the example to be more aligned with their docs.

**Comment by empz** [comment]
> Hey, we basically don't need this function at all. However since next-intl is now more strict about it's usage, I'll updated the example to be more aligned with their docs.

Thanks for the quick action. I'm trying to implement the changes you've made in the next example app in that PR, but it looks like I have a somewhat different setup.
I've followed the [guide from the official docs](https://tolgee.io/js-sdk/integrations/react/next/app-router) which doesn't seem to be doing the same as the example app.

Applying your changes in this setup results in the following server-side error:
```
Error: No messages found. Have you configured them correctly? See https://next-intl-docs.vercel.app/docs/configuration#messages
    at async LocaleLayout (./src/app/[locale]/layout.tsx:55:21)
```

It's not clear to me whether I need the actual files (messages/en.json,es.json,etc) during developmnent or not). I was under the impression that these were fetched from the Tolgee API in development.

**Comment by empz** [comment]
Ok, so I've added the www namespace into the getRequestConfig function like so:
```ts
export default getRequestConfig(async ({ locale }) => {
  return {
    // it's important you provide all data which are needed for initial render
    // so current locale and also fallback locales + necessary namespaces
    messages: await getStaticData(["en", locale], ["www"]),
  };
});
```
It seems to be working now, but I'm getting some errors in the server console which I wasn't getting before this change.
```
IntlError: INVALID_KEY: Namespace keys can not contain the character "." as this is used to express nesting. Please remove it or replace it with another character.

Invalid keys: hero.description (at en:www), hero.title (at en:www), hero.description (at es:www), hero.title (at es:www)

If you're migrating from a flat structure, you can convert your messages as follows:

import {set} from "lodash";

const input = {
  "one.one": "1.1",
  "one.two": "1.2",
  "two.one.one": "2.1.1"
};

const output = Object.entries(input).reduce(
  (acc, [key, value]) => set(acc, key, value),
  {}
);

// Output:
//
// {
//   "one": {
//     "one": "1.1",
//     "two": "1.2"
//   },
//   "two": {
//     "one": {
//       "one": "2.1.1"
//     }
//   }
// }

    at validateMessages (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/initializeConfig-o7L_y07P.js:148:13)    
    at initializeConfig (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/initializeConfig-o7L_y07P.js:166:7)     
    at eval (webpack-internal:///(rsc)/./node_modules/next-intl/dist/esm/server/react-server/getConfig.js:10:1993)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eval (webpack-internal:///(rsc)/./node_modules/next-intl/dist/esm/server/react-server/getLocale.js:8:80) {
  code: 'INVALID_KEY',
  ```
  
  I'm assuming the previous implementation wasn't really using next-intl to load the keys and was just using it for the routing part. This change seems to be making full use of `next-intl` which doesn't seem to allow dots in the keys name inside a namespace (even though the Tolgee UI has no problem with it).

**Comment by empz** [comment]
Sorry for all these messages, I'm just thinking out loud while I share my findings in case they serve as feedback.

I see the problem is that next-intl doesn't allow dots in key names because they use a hierarchical structure, not a flat one and dots are the way to traverse through the this hierarchy. I went that route when named my keys in Tolgee, unconsciously and without knowing how next-intl does it. But now my keys are incompatible with next-intl because of this.

I think hierarchical structure is a good way to approach this but I'm guessing Tolgee doesn't really support that. Just namespacing + flat list.

I'll rename my keys now. Maybe add a note in the Next.js integration docs to avoid using dots in key names as that will make next-intl complain.

**Comment by stepan662** [comment]
Hmm, maybe this was a bit rushed. I thought the next-intl wouldn't touch the data, but apparently it does. That's unfortunate. You don't necessarly need to rename your keys. You can simply load your translations outside of next-intl like it was before. With `await getStaticData()` directly in the layout instead of `getMessages`.

**Comment by stepan662** [comment]
I'll probably revert the change back the way it was.

**Comment by stepan662** [comment]
Ok, I've reverted both example app and docs. It should now work fine and without any warnings.

**Comment by empz** [comment]
> Ok, I've reverted both example app and docs. It should now work fine and without any warnings.

Thank you, it's working now with no warnings (after 

There are a couple inconsistencies still though.

1. In the docs, `src/app/layout.tsx` uses `notFound()` which is not supported in Next.js. Should be changed to the strategy used in the example app. 
![image](https://github.com/user-attachments/assets/525d4cd3-667f-4c9e-86e0-56f0bc0e3072)
![image](https://github.com/user-attachments/assets/e1e90f5a-f929-4e6c-8ffe-b90c182cfa82)


2. Folder structure in the docs is inconsistent with the code in `tolgee/shared.ts`
![image](https://github.com/user-attachments/assets/e45aa788-692c-4a64-9cd6-59049f7724ce)
![image](https://github.com/user-attachments/assets/92efb8d9-547d-412c-99de-324f00aa9aa9)

3. Implementation of `getStaticData` is different in both.
![image](https://github.com/user-attachments/assets/8b398d47-4485-48e5-8b0f-31f9c2645761)
![image](https://github.com/user-attachments/assets/6f3117ae-bbfb-45d3-8248-8d4c46861d5d)

**Comment by empz** [comment]
I can create a PR to fix the docs if you want.

**Comment by stepan662** [comment]
1. Ah, you are right it's referring to a wrong file, it should refer to `/app/[locale]/layout.tsx`, but other than that I think it's correct.
2. I believe you were too fast for me, the example app was not yet released, I think now it's correct
3. This was actually intentional, to keep the docs a bit simpler, however it might be confusing, so I guess it will be better to show full implementation

If it's just these three points, I can fix it myself.

**Comment by empz** [comment]
> 1. Ah, you are right it's referring to a wrong file, it should refer to `/app/[locale]/layout.tsx`, but other than that I think it's correct.
> 2. I believe you were too fast for me, the example app was not yet released, I think now it's correct
> 3. This was actually intentional, to keep the docs a bit simpler, however it might be confusing, so I guess it will be better to show full implementation
> 
> If it's just these three points, I can fix it myself.

Could you please add an example that includes namespaces?

When I do "tolgee pull", the downloaded locale data come inside a namespace folder. I have only one namespace for now (but I'll create more soon).
This particular Next.js project should use only the "www" namespace. My resulting structure is as follows:
![image](https://github.com/user-attachments/assets/c7ddcc51-3ffb-404e-8e29-ad01ab2266a4)

But it doesn't seem to be picked up by the Tolgee SDK as I get the following warning (I have only en and es set).
```
Tolgee: Missing records in "staticData" for proper SSR functionality: "www:es", "www:es", "www:en", "www:en"
```

Running a production build works, but I can see the server components are not being SSRed (all the text is inside <script> tags).

I've tried setting `defaultNs: "www"` everywhere (tolgee/client.tsx, server.tsx and shared.ts), but that didn't worked.

**Comment by empz** [comment]
Ok, nevermind, I got it working by following the example app file by file. I simply needed to add ["www"] as an extra parameter to every call of `getStaticData`.

I still think the integration guide could be improved.

Thanks
