### ISSUE TITLE
Use 'defaultValue' as a placeholder for base language in incontext Translation UI 

### ISSUE THREAD

**Issue by cfmano** [tolgee/tolgee-js#3378]
When trying to translate a new (not yet existing key) using Tolgee dev tools and InContext translation UI, it would be great to display the content of element's defaultValue as sort of placeholder value.

In situations, when interpolations and/or parameters are used, the translator has no clue, what format and parameter to use, as they only get an empty text inputs:

![image](https://github.com/user-attachments/assets/9fc5bf01-8bbf-439e-a41c-725784b5e55e)

So, such kind of placeholder for default values would be very usefull, also maybe showing it in all cases would be great, so translators can compare what was the difference between original (inlined) message and their version:

![image](https://github.com/user-attachments/assets/9c009dff-e2d2-4f69-9c3f-7500f6bd2a1b)

**Comment by stepan662** [comment]
Hey, we've got this implemented (default value should be prefilled in the base language field), however it got somehow broken.
https://github.com/tolgee/tolgee-js/pull/3402
