### ISSUE TITLE
Calling client side code from server side

### ISSUE THREAD

**Issue by alvarolozano** [tolgee/tolgee-js#3400]
The ``detectLanguageFromHeaders`` is supposed to be a **SERVER** function, but it is calling the ``detectLanguage`` function which is supposed to be a **CLIENT** function

https://github.com/tolgee/tolgee-js/blob/358707421c721a0454f6be9d2963ccf27820ba76/packages/web/src/package/tools/detectLanguageFromHeaders.ts#L9

So this line makes the initialization to fail, because it is calling the window object from the server.
https://github.com/tolgee/tolgee-js/blob/358707421c721a0454f6be9d2963ccf27820ba76/packages/web/src/package/LanguageDetector.ts#L13

**Comment by alvarolozano** [comment]
Mentioned in https://github.com/tolgee/tolgee-js/pull/3401

**Comment by alvarolozano** [comment]
Possibly fixed in https://github.com/tolgee/tolgee-js/pull/3401

**Comment by stepan662** [comment]
Fixed in #3401
